apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: nginx
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/Gavin-Garley/busybox.git
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true